### ISSUE TITLE
Lav script der henter 5 datakilder 

### ISSUE THREAD

**Issue by johan-ejstrud** [johan-ejstrud/ruuk#4]
Lav script der henter 5 datasæt der kunne være interessante at lave visualiseringer med.

Scriptet skal bruges, så folk bare kan copy-paste koden og gå direkte i gang med at lave visualiseringer.

**Comment by dataniel** [comment]
Jeg skulle gerne have uploaded 3 tabeller nu. De resterende kommer senere :-)

**Comment by dataniel** [comment]
De resterende kommer senere ...
