### ISSUE TITLE
Lav 5 plots i stigende sværhedsgrad (Daniel)

### ISSUE THREAD

**Issue by johan-ejstrud** [johan-ejstrud/ruuk#7]
Vi laver hver 5 plots i stigende sværhedsgrad. Målet er at folk med det rette data skal kunne reproducere plotene.

Til de mere basale, kan man bruge de teknikker der er i [Johans ggplot lektion](https://www.youtube.com/watch?v=nQ3yCbQWVz0).

**Comment by johan-ejstrud** [comment]
Hey @dataniel jeg prøvede at reverse engineere dine plots. Det var virkelig sjovt! 😀 Det er en super god opgave du har fundet på. 👌

Det kan se hvor tæt jeg kom på i mappen [img/meetup2](https://github.com/johan-ejstrud/ruuk/tree/main/img/meetup2).

Du kan se min kode i [ggplot_reverse_engineer_daniels_plots.R](https://github.com/johan-ejstrud/ruuk/blob/main/R/meetup2/ggplot_reverse%20engineer_daniels_plots.R),

Mit tidsforbrug var
- Plot1: 29 min
- Plot2: 19 min
- Plot3: 13 min

Jeg har nogle inputs til hvad der var sjovt og knap så sjovt at reverse engineere, men jeg tænker lige at jeg selv laver 3 plots som du kan prøve at reverse engineere, og så kan vi snakke sammen efter det. 😀

**Comment by johan-ejstrud** [comment]
- Level 2: Lineplot med kvote vs. fangst
- Line1: Lineplot vækst i bnp

**Comment by dataniel** [comment]
se ny fil, Daniel_Ruuk2.R # github-noob
